### PR TITLE
Quote "OFF" so that YAML does not interpret it as false

### PR DESCRIPTION
**Pull request by mvidner**
Described eg. in
https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#true-false-yes-no-on-off
actually seen in Ruby

### CODE REVIEW

**Comment by dlech** [comment]
Thanks!

**Comment by dlech** [comment]
You've got me curious... what are you doing with Ruby and EV3 byte codes?

**Comment by mvidner** [comment]
Thanks!
Well, my goal is to interact with the stock firmware using Ruby. It is still WIP but I have put together an assembler / compiler that can do simple things so far:

VernierReadout.lms, taken from the lms2012 sources:
```asm
define    PORT      1

vmthread  MAIN
{
  DATA32  Timer
  DATA32  Data1
  DATAS   String 8
  
Loop:

  UI_DRAW(FILLWINDOW,0x00,0,0)
  UI_DRAW(SELECT_FONT,SMALL_FONT)
  UI_DRAW(TEXT,FG_COLOR,0,10,'Vernier Readout  V0.00')

  UI_DRAW(TEXT,FG_COLOR,0,50,'Raw 1')
  UI_DRAW(SELECT_FONT,NORMAL_FONT)
  
  INPUT_DEVICE(READY_RAW,0,PORT,1,0,1,Data1)

  AND32(Data1,0xFFFF,Data1)
  STRINGS(NUMBER_FORMATTED,Data1,'%-5d',8,String)
  UI_DRAW(TEXT,FG_COLOR,64,50,String)
  
  UI_DRAW(UPDATE)
  
  TIMER_WAIT(250,Timer)
  TIMER_READY(Timer)

  JR(Loop)
}
```

VernierReadout.rb, producing an identical `rbf` file:
```rb
PORT = 1

vmthread :MAIN do
  data32 :Timer
  data32 :Data1
  datas :String, 8

  self.loop do
    ui_draw(FILLWINDOW, 0x00, 0, 0)
    ui_draw(SELECT_FONT, SMALL_FONT)
    ui_draw(TEXT, FG_COLOR, 0, 10, 'Vernier Readout  V0.00')

    ui_draw(TEXT, FG_COLOR, 0, 50, 'Raw 1')
    ui_draw(SELECT_FONT, NORMAL_FONT)

    input_device(READY_RAW, 0, PORT, 1, 0, 1, :Data1)

    and32(:Data1, 0xFFFF, :Data1)
    strings(NUMBER_FORMATTED, :Data1, '%-5d', 8, :String)
    ui_draw(TEXT, FG_COLOR, 64, 50, :String)

    ui_draw(UPDATE)

    timer_wait(250, :Timer)
    timer_ready(:Timer)
  end
end
```

I hope to publish something useful this month.

**Comment by mvidner** [comment]
@dlech It took longer, but here it is: https://github.com/mvidner/lignite

**Comment by dlech** [comment]
Cool. I'll have to give it a try.

**Pull request merged**
